//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Occasion
    {
        public Occasion()
        {
            this.Wardrobes = new HashSet<Wardrobe>();
        }
    


        [Display (Name ="Occasions")]
        public int OccasionsID { get; set; }

        [Display (Name ="Occasion")]
        public string Occasion1 { get; set; }
    
        public virtual ICollection<Wardrobe> Wardrobes { get; set; }
    }
}
