//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Wardrobe
    {
        public int WardrodeID { get; set; }

        [Display (Name= "Name")]
        public string FirstName { get; set; }

        [Display (Name = "Boutique/Store")]
        public string LastName { get; set; }

        [Display (Name ="Color")]
        public int ColorsID { get; set; }

        [Display (Name ="Item")]
        public int ItemsID { get; set; }

        [Display (Name ="Occasion")]
        public int OccasionsID { get; set; }

        [Display (Name ="Season")]
        public int SeasonsID { get; set; }

        [Display (Name ="Photo")]
        public string Photos { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Item Item { get; set; }
        public virtual Occasion Occasion { get; set; }
        public virtual Season Season { get; set; }
    }
}
